feat: statsd deploy statistics
avast/labmanager-unit-vsphere pull request #107
Opened 2022-12-07 11:54 UTC by ireznice

2022-12-07 12:51 UTC, petrSchreiber requested changes
🙏 Please remove the commented section and I will merge the final version at lightspeed

2022-12-07 12:51 UTC, petrSchreiber commented on vc-worker.py
> +
Fantastic improvement in the code, please just remove this commented out part.

2022-12-08 11:53 UTC, petrSchreiber approved these changes
🎖️ Significant improvement, thank you

2022-12-12 08:54 UTC, timsta0 approved these changes
tested on stage 👍

2022-12-12 08:56 UTC, merged