fix: ldap auth module
avast/labmanager-unit-vsphere pull request #66
Opened 2021-03-18 15:35 UTC by ireznice

2021-03-18 15:50 UTC, petrSchreiber requested changes
Minor issue

2021-03-18 15:50 UTC, petrSchreiber commented on web/middleware/auth_ldap.py
> +                "An exception occured when connecting to ldap: {}".format(ex)
```suggestion
                "An exception occured when connecting to ldap: {}".format(iex)
```

2021-03-19 10:01 UTC, ireznice commented on web/middleware/auth_ldap.py
> +                "An exception occured when connecting to ldap: {}".format(ex)
fixed

2021-03-24 08:21 UTC, petrSchreiber approved these changes

2021-03-24 08:21 UTC, merged